let myjokes = 
  [
    {
      category: "Programming",
      type: "single",
      joke: "The six stages of debugging:\n1. That can't happen.\n2. That doesn't happen on my machine.\n3. That shouldn't happen.\n4. Why does that happen?\n5. Oh, I see.\n6. How did that ever work?",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 122,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "Your momma is so fat, you need to switch to NTFS to store a picture of her.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 54,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: '"We messed up the keming again guys."',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 20,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: 'Today I learned that changing random stuff until your program works is "hacky" and a "bad coding practice" but if you do it fast enough it\'s "Machine Learning" and pays 4x your current salary.',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 33,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: 'Two SQL tables sit at the bar. A query approaches and asks "Can I join you?"',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 220,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "Hey Girl,\nRoses are #ff0000,\nViolets are #0000ff,\nI use hex codes,\nBut I'd use RGB for you.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 41,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: 'Judge: "I sentence you to the maximum punishment..."\nMe (thinking): "Please be death, please be death..."\nJudge: "Learn Java!"\nMe: "Damn."',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 45,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "Java and C were telling jokes. It was C's turn, so he writes something on the wall, points to it and says \"Do you get the reference?\" But Java didn't.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 4,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 27,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "The generation of random numbers is too important to be left to chance.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 39,
      safe: true,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup:
        "I'm sure good looking lesbians look at fat lesbians and give them no chance.",
      delivery: "Until they see their fingers.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 163,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "twopart",
      setup: "Why did the programmer quit his job?",
      delivery: "Because he didn't get arrays.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 16,
      safe: true,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup:
        "I'm thinking of setting up a comedy group to help people going through cancer treatment.",
      delivery: 'I\'ll call it "A Sense of Tumor".',
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 96,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: 'Today I learned that changing random stuff until your program works is "hacky" and a "bad coding practice" but if you do it fast enough it\'s "Machine Learning" and pays 4x your current salary.',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 33,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "twopart",
      setup:
        "Why did the Python programmer not respond to the foreign mails he got?",
      delivery: "Because his interpreter was busy collecting garbage.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 15,
      safe: true,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup: "How many nice guys does it take to change a lightbulb?",
      delivery:
        "None, they'll just compliment it and get pissed off when it won't screw.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 90,
      safe: false,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup: "What is the difference between a pizza and a black man?",
      delivery: "A pizza can feed a family of five.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: false,
      },
      id: 173,
      safe: false,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "What do you call a deer with no eyes?",
      delivery: "No eye deer.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 209,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "There are only 10 kinds of people in this world: those who know binary and those who don't.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 35,
      safe: true,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup: "9/11 jokes are not funny.",
      delivery: "The other 2 though, are hilarious!",
      flags: {
        nsfw: false,
        religious: false,
        political: true,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 76,
      safe: false,
      lang: "en",
    },
  ];



let index = Math.floor(Math.random() * myjokes.length)
joke.innerHTML = myjokes[index].joke